import { config } from "dotenv";

config();

export const {
  PORT,
  NODE_ENV,
  BASE_URL,
  JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_NAME,
  DB_HOST,
  DB_DIALECT,
  DB_SSL_MODE,
  DB_CA_CERTIFICATE,
  EMAIL_USER,
  EMAIL_PASS,
  SITE_URL,
  JWT_EXPIRES_IN,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_NAME,
} = process.env;
